# Generated by Django 5.2.7 on 2025-11-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uer',
            new_name='User',
        ),
    ]
