# Generated by Django 5.2.7 on 2025-11-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('horroe', 'horror'), ('action', 'action'), ('romance', 'romance')], max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=40)),
            ],
        ),
    ]
