# Generated by Django 5.2.7 on 2025-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymodel',
            name='category',
            field=models.CharField(choices=[('horror', 'horror'), ('action', 'action'), ('romance', 'romance')], max_length=30),
        ),
    ]
